# Generated by Django 5.2.4 on 2025-07-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0002_queue_served_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='name',
            field=models.CharField(max_length=31),
        ),
    ]
