# Generated by Django 5.2.4 on 2025-07-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0003_alter_queue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
