# Generated by Django 5.2.4 on 2025-07-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0004_queue_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='info',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
