# Generated by Django 5.2.4 on 2025-07-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0005_customer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='queue_codes/'),
        ),
    ]
