# Generated by Django 5.2.4 on 2025-07-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0006_queue_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
