# Generated by Django 5.2.4 on 2025-07-20 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0007_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='total_wait_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
