# Generated by Django 5.2.4 on 2025-07-20 15:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0009_queue_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['pk']},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('queue', 'user')},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='position',
        ),
    ]
