# Generated by Django 5.2.4 on 2026-03-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueapp", "0011_customer_public_key_queue_public_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="public_key_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="queue",
            name="public_key_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="CustomerNoteNonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nonce", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_nonces",
                        to="queueapp.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("customer", "nonce")},
            },
        ),
    ]
