# Generated by Django 5.2.4 on 2026-03-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueapp", "0012_customer_public_key_version_queue_public_key_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="qr_language",
            field=models.CharField(default="sk", max_length=8),
        ),
    ]
