"""
Django settings for Virtual Queue project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from logging.handlers import RotatingFileHandler
import dj_database_url


def get_env_var(var_name):
    value = os.environ.get(var_name)
    if value is None:
        raise ImproperlyConfigured(f"Missing required environment variable: {var_name}")
    return value


BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = get_env_var('DJANGO_SECURE_STRING')

DOMAIN_NAME = get_env_var('DOMAIN_NAME')
WWW_DOMAIN_NAME = f"www.{DOMAIN_NAME}"
HTTPS_DOMAIN_NAME = f"https://{DOMAIN_NAME}"
HTTPS_WWW_DOMAIN_NAME = f"https://www.{DOMAIN_NAME}"
APP_NAME = DOMAIN_NAME.split('.')[0]
DATABASE_URL = get_env_var("DATABASE_URL")

DEBUG = False

ALLOWED_HOSTS = [
	DOMAIN_NAME,
	WWW_DOMAIN_NAME, 
]

CSRF_TRUSTED_ORIGINS = [
    HTTPS_DOMAIN_NAME,
    HTTPS_WWW_DOMAIN_NAME,
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'queueapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = f'{APP_NAME}.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = f'{APP_NAME}.wsgi.application'


DATABASES = {
    "default": dj_database_url.config(
        default=DATABASE_URL
    )
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} ({filename}:{lineno}) - {message}',
            'style': '{',
        },
    },

    'handlers': {
        'django_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'django.log',
            'maxBytes': 10 * 1024 * 1024, 
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },

    'loggers': {
        'django': {
            'handlers': ['django_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['django_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'queueapp': {
            'handlers': ['django_file'],
            'level': 'INFO',
            'propagate': False,
        },
        '': {
            'handlers': ['django_file'],  # root logger: catches everything else
            'level': 'DEBUG',
        },
    },
}

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'sk'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365 # 1 year in seconds

